export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const LOGIN_ERROR_MESSAGE_READ = 'LOGIN_ERROR_MESSAGE_READ';

export const SORTING_PRODUCTS_TYPE_CHANGED = 'SORTING_TYPE_CHANGED';